title:              I'm SeungHwan-Jeon, Developer.
email:              tmd4347@gmail.com
description:        개발자 전승환의 블로그입니다.
author:             전승환
baseurl:            ""
url:                "https://dev-seunghwanjeon.github.io"

# Social Profiles
twitter_username:   
github_username:    DEV-SeungHwanJeon
facebook_username:  전승환
instagram_username:  i.m.seunghwan
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
